name: Generate Contribution Snake

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: velmurugansurendhar123-dotcom
          outputs: |
            github-snake.svg?color_snake=FF6EC7&color_dots=#171321,#342044,#6B3FA0,#C77DFF,#FF6EC7

      - name: Commit Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution snake"
          default_author: github_actions
